///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesBlueBall = 'assets/images/blue-ball.png';
  static const String imagesEarth = 'assets/images/earth.png';
  static const String imagesJupiter = 'assets/images/jupiter.png';
  static const String imagesMars = 'assets/images/mars.png';
  static const String imagesMenuIcon = 'assets/images/menu_icon.png';
  static const String imagesMercury = 'assets/images/mercury.png';
  static const String imagesNeptune = 'assets/images/neptune.png';
  static const String imagesSaturn = 'assets/images/saturn.png';
  static const String imagesUranus = 'assets/images/uranus.png';
  static const String imagesVenus = 'assets/images/venus.png';
}
